INSERT INTO users (name, age) VALUES ("Matteo", "25");
INSERT INTO users (name, age) VALUES ("Kevin", "27");
INSERT INTO users (name, age) VALUES ("Vale", "28");
INSERT INTO users (name, age) VALUES ("Anto", "58");
INSERT INTO users (name, age) VALUES ("Fra", "27");
INSERT INTO users (name, age) VALUES ("Molly", "6");
INSERT INTO users (name, age) VALUES ("Marti", "28");
INSERT INTO users (name, age) VALUES ("Erika", "25");
INSERT INTO users (name, age) VALUES ("Pollo", "27");
INSERT INTO users (name, age) VALUES ("Martina", "25");
INSERT INTO users (name, age) VALUES ("Mirella", "70");
INSERT INTO users (name, age) VALUES ("Venere", "82");
INSERT INTO users (name, age) VALUES ("Raffaele", "87");
INSERT INTO users (name, age) VALUES ("Romeo", "57");
INSERT INTO users (name, age) VALUES ("Daniele", "25");
INSERT INTO users (name, age) VALUES ("Jorge", "31");
INSERT INTO users (name, age) VALUES ("Aitor", "32");
INSERT INTO users (name, age) VALUES ("Stefano", "31");
INSERT INTO users (name, age) VALUES ("Semola", "13");
INSERT INTO users (name, age) VALUES ("Giulio", "12");



INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Palatino", "Urbanistic", "10000", "12/21/2017", "2/21/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Venere", "Spacial", "2000000", "1/26/2017", "2/26/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Scale", "Urbanistic", "3000", "2/22/2017", "2/27/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Animalier", "Fashion", "3400000", "07/21/2017", "9/21/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Acne", "Dermatologic", "700", "3/7/2017", "2/21/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mamma", "House", "100000", "7/5/2017", "2/21/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mykonos", "Leisure", "1200", "7/5/2017", "1/7/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wedding", "Leisure", "22000", "1/10/2017", "17/9/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Vespa", "Transportation", "1200", "1/10/2017", "30/11/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Botox", "Dermatologic", "200", "7/5/2017", "5/9/2017");


INSERT INTO pledges (amount, user_id, project_id) VALUES ("2000", 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("4000", 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("250000", 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("2000", 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("147000", 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("200", 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("400", 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("100", 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("150", 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("230000", 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("1000000", 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("60", 8, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("200", 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("100", 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("50", 11, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("200", 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("20000", 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("3000", 9, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("10000", 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("50000", 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("400", 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("350", 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("7000", 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("7000", 20, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("2000", 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("600", 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("400", 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("300", 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("300", 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ("50", 12, 9);
